- name: Creates directory Sample
  hosts: all
  tasks:
    - name: ensure file exists
      copy:
      content: ""
      dest: /etc/nologin
      force: no
      group: sys
      owner: root
      mode: 0555
