- name: Creates directory Sample
  hosts: all
  tasks:
    - name: Creates directory
      copy:
      content: ""
      dest: /etc/nologin
      force: no
      group: sys
      owner: root
      mode: 0555
